FROM alpine

RUN apk add --no-cache openssh-client

COPY ./windows /root/.ssh/id_rsa

CMD trap '' INT TSTP; while true; do ssh -t -L 2375:${WINDOWS_ENDPOINT}:2375 -q -o StrictHostKeyChecking=no Administrator@${WINDOWS_ENDPOINT} powershell; done
