FROM docker:1.12.3-experimental-dind

RUN apk add --no-cache bash git tmux py-pip apache2-utils vim \
    && pip install 'docker-compose==1.8.0'

COPY ["docker-prompt","/usr/local/bin/"]
COPY [".vimrc",".bashrc", "./root/"]

